export enum NotificationType {
  NEW_CANDIDATE = 'new_candidate',
  STATE_CHANGED = 'state_changed',
  INTERVIEW_PLANNED = 'interview_planned',
  INTERVIEW_UPDATED = 'interview_updated',
  INTERVIEW_CANCELLED = 'interview_cancelled',
  DOCUMENT_UPLOADED = 'document_uploaded',
  DOCUMENT_PROCESSED = 'document_processed',
  DOCUMENT_ASSOCIATED = 'document_associated',
  SKILLS_EXTRACTED = 'skills_extracted',
  SKILL_ASSOCIATED = 'skill_associated',
  FORM_CREATED = 'form_created',
  FORM_UPDATED = 'form_updated',
  JOB_OFFER_CREATED = 'job_offer_created',
  JOB_OFFER_UPDATED = 'job_offer_updated',
  USER_ADDED_TO_ORGANIZATION = 'user_added_to_organization',
  USER_ROLE_CHANGED = 'user_role_changed',
}
